"""add_generation_and_escasez_cols

Revision ID: ab8330540d1b
Revises: eb8fd264527a
Create Date: 2026-03-04 00:56:03.783929

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ab8330540d1b'
down_revision: Union[str, None] = 'eb8fd264527a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('market_data', sa.Column('precio_escasez_cop', sa.Float(), nullable=True))
    op.add_column('market_data', sa.Column('gen_hidraulica_gwh', sa.Float(), nullable=True))
    op.add_column('market_data', sa.Column('gen_termica_gwh', sa.Float(), nullable=True))
    op.add_column('market_data', sa.Column('gen_solar_gwh', sa.Float(), nullable=True))
    op.add_column('market_data', sa.Column('gen_eolica_gwh', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('market_data', 'gen_eolica_gwh')
    op.drop_column('market_data', 'gen_solar_gwh')
    op.drop_column('market_data', 'gen_termica_gwh')
    op.drop_column('market_data', 'gen_hidraulica_gwh')
    op.drop_column('market_data', 'precio_escasez_cop')
    # ### end Alembic commands ###
