"""initial_schema

Revision ID: eb8fd264527a
Revises: 
Create Date: 2026-03-02 04:54:19.620386

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'eb8fd264527a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('sic_code', sa.String(length=8), nullable=False),
    sa.Column('risk_profile', sa.String(length=20), nullable=False),
    sa.Column('resources', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('installed_capacity_mw', sa.Float(), nullable=True),
    sa.Column('variable_cost_cop_kwh', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agents_sic_code'), 'agents', ['sic_code'], unique=True)
    op.create_table('features_cache',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('features_json', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('target_price', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('timestamp')
    )
    op.create_index('ix_features_cache_timestamp', 'features_cache', ['timestamp'], unique=False)
    op.create_table('market_data',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('spot_price_cop', sa.Float(), nullable=False),
    sa.Column('demand_mwh', sa.Float(), nullable=False),
    sa.Column('hydrology_pct', sa.Float(), nullable=False),
    sa.Column('reservoir_level_pct', sa.Float(), nullable=False),
    sa.Column('thermal_dispatch_pct', sa.Float(), nullable=False),
    sa.Column('agent_sic_code', sa.String(length=8), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_market_data_agent_ts', 'market_data', ['agent_sic_code', 'timestamp'], unique=False)
    op.create_index('ix_market_data_timestamp', 'market_data', ['timestamp'], unique=False)
    op.create_table('model_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('task', sa.String(length=100), nullable=False),
    sa.Column('algorithm', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('stage', sa.String(length=20), nullable=False),
    sa.Column('artifact_path', sa.String(length=500), nullable=False),
    sa.Column('metrics', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('params', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('feature_schema', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('is_champion', sa.Boolean(), nullable=False),
    sa.Column('trained_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('trained_on_days', sa.Integer(), nullable=False),
    sa.Column('promoted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('promoted_by', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_model_versions_champion', 'model_versions', ['task', 'is_champion'], unique=False)
    op.create_index('ix_model_versions_task_stage', 'model_versions', ['task', 'stage'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_sic_code', sa.String(length=8), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('model_version_id', sa.UUID(), nullable=False),
    sa.Column('horizon_hours', sa.Integer(), nullable=False),
    sa.Column('hourly_predictions', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('actuals', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('overall_confidence', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_predictions_agent_ts', 'predictions', ['agent_sic_code', 'generated_at'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_sic_code', sa.String(length=8), nullable=False),
    sa.Column('prediction_id', sa.UUID(), nullable=True),
    sa.Column('model_version_id', sa.UUID(), nullable=True),
    sa.Column('recommended_offer_price_cop', sa.Float(), nullable=False),
    sa.Column('confidence', sa.String(length=10), nullable=False),
    sa.Column('risk_level', sa.String(length=10), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('key_factors', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('hourly_offers', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('llm_model_used', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_recommendations_agent_ts', 'recommendations', ['agent_sic_code', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_recommendations_agent_ts', table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index('ix_predictions_agent_ts', table_name='predictions')
    op.drop_table('predictions')
    op.drop_index('ix_model_versions_task_stage', table_name='model_versions')
    op.drop_index('ix_model_versions_champion', table_name='model_versions')
    op.drop_table('model_versions')
    op.drop_index('ix_market_data_timestamp', table_name='market_data')
    op.drop_index('ix_market_data_agent_ts', table_name='market_data')
    op.drop_table('market_data')
    op.drop_index('ix_features_cache_timestamp', table_name='features_cache')
    op.drop_table('features_cache')
    op.drop_index(op.f('ix_agents_sic_code'), table_name='agents')
    op.drop_table('agents')
    # ### end Alembic commands ###
