"""fix_recommendation_model_fields

Revision ID: edbd8c5798b0
Revises: bd630a1c569f
Create Date: 2026-03-04 02:21:43.861764

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'edbd8c5798b0'
down_revision: Union[str, None] = 'bd630a1c569f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recommendations', sa.Column('narrative', sa.Text(), nullable=False))
    op.add_column('recommendations', sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False))
    op.drop_index(op.f('ix_recommendations_agent_ts'), table_name='recommendations')
    op.create_index('ix_recommendations_agent_ts', 'recommendations', ['agent_sic_code', 'generated_at'], unique=False)
    op.drop_column('recommendations', 'created_at')
    op.drop_column('recommendations', 'confidence')
    op.drop_column('recommendations', 'recommended_offer_price_cop')
    op.drop_column('recommendations', 'valid_until')
    op.drop_column('recommendations', 'rationale')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recommendations', sa.Column('rationale', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('recommendations', sa.Column('valid_until', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('recommendations', sa.Column('recommended_offer_price_cop', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('recommendations', sa.Column('confidence', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    op.add_column('recommendations', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_index('ix_recommendations_agent_ts', table_name='recommendations')
    op.create_index(op.f('ix_recommendations_agent_ts'), 'recommendations', ['agent_sic_code', 'created_at'], unique=False)
    op.drop_column('recommendations', 'generated_at')
    op.drop_column('recommendations', 'narrative')
    # ### end Alembic commands ###
